scientist ="https://assets2.lottiefiles.com/packages/lf20_jaejabqz.json"
ES_light_statistic = "https://assets10.lottiefiles.com/private_files/lf30_lhnmhnbn.json" 
ES_lightball = "https://assets4.lottiefiles.com/packages/lf20_o1p93l2m.json"
ES_video = "https://www.youtube.com/watch?v=9yKRz08buaA"
GD_SF = "https://assets10.lottiefiles.com/private_files/lf30_dvqxua.json"
GD_MF = "https://assets10.lottiefiles.com/packages/lf20_thq99fhd.json"
GD_CO = "https://assets10.lottiefiles.com/private_files/lf30_ljfP8c.json"
GD_video = "https://www.youtube.com/watch?v=nesNYAcjw-g"
GD_main = "https://assets8.lottiefiles.com/packages/lf20_rbdxztbu.json"
GD_main_2 = "https://assets4.lottiefiles.com/private_files/lf30_psn7xxju.json"
GD_wind = "https://assets8.lottiefiles.com/private_files/lf30_yi91simh.json"
GD_solar = "https://assets2.lottiefiles.com/packages/lf20_lf6sg88x.json"
